namespace Parser.Helpers.Enums
{
    public enum LogEventsEnum : byte
    {

        AP_STATE                      = 7,
        SYSTEM_TIME_SET               = 8,
        INIT_SIMPLE_BEARING           = 9,
        ARMED                         = 10,
        DISARMED                      = 11,
        AUTO_ARMED                    = 15,
        LAND_COMPLETE_MAYBE           = 17,
        LAND_COMPLETE                 = 18,
        NOT_LANDED                    = 28,
        LOST_GPS                      = 19,
        FLIP_START                    = 21,
        FLIP_END                      = 22,
        SET_HOME                      = 25,
        SET_SIMPLE_ON                 = 26,
        SET_SIMPLE_OFF                = 27,
        SET_SUPERSIMPLE_ON            = 29,
        AUTOTUNE_INITIALISED          = 30,
        AUTOTUNE_OFF                  = 31,
        AUTOTUNE_RESTART              = 32,
        AUTOTUNE_SUCCESS              = 33,
        AUTOTUNE_FAILED               = 34,
        AUTOTUNE_REACHED_LIMIT        = 35,
        AUTOTUNE_PILOT_TESTING        = 36,
        AUTOTUNE_SAVEDGAINS           = 37,
        SAVE_TRIM                     = 38,
        SAVEWP_ADD_WP                 = 39,
        FENCE_ENABLE                  = 41,
        FENCE_DISABLE                 = 42,
        ACRO_TRAINER_OFF              = 43,
        ACRO_TRAINER_LEVELING         = 44,
        ACRO_TRAINER_LIMITED          = 45,
        GRIPPER_GRAB                  = 46,
        GRIPPER_RELEASE               = 47,
        PARACHUTE_DISABLED            = 49,
        PARACHUTE_ENABLED             = 50,
        PARACHUTE_RELEASED            = 51,
        LANDING_GEAR_DEPLOYED         = 52,
        LANDING_GEAR_RETRACTED        = 53,
        MOTORS_EMERGENCY_STOPPED      = 54,
        MOTORS_EMERGENCY_STOP_CLEARED = 55,
        MOTORS_INTERLOCK_DISABLED     = 56,
        MOTORS_INTERLOCK_ENABLED      = 57,
        ROTOR_RUNUP_COMPLETE          = 58, // Heli only
        ROTOR_SPEED_BELOW_CRITICAL    = 59, // Heli only
        EKF_ALT_RESET                 = 60,
        LAND_CANCELLED_BY_PILOT       = 61,
        EKF_YAW_RESET                 = 62,
        AVOIDANCE_ADSB_ENABLE         = 63,
        AVOIDANCE_ADSB_DISABLE        = 64,
        AVOIDANCE_PROXIMITY_ENABLE    = 65,
        AVOIDANCE_PROXIMITY_DISABLE   = 66,
        GPS_PRIMARY_CHANGED           = 67,
        WINCH_RELAXED                 = 68,
        WINCH_LENGTH_CONTROL          = 69,
        WINCH_RATE_CONTROL            = 70,
        ZIGZAG_STORE_A                = 71,
        ZIGZAG_STORE_B                = 72,
        LAND_REPO_ACTIVE              = 73,
        STANDBY_ENABLE                = 74,
        STANDBY_DISABLE               = 75,
        SURFACED                      = 163,
        NOT_SURFACED                  = 164,
        BOTTOMED                      = 165,
        NOT_BOTTOMED                  = 166
    }
}